#methods of creating a tuple
new_tuple=('a','b','c','d','e')
print(new_tuple)
new_tuple1=('a')
print(new_tuple1)
new_tuple2=('a',)
print(new_tuple2)
new_tuple3=tuple()
print(new_tuple3)
new_tuple4=tuple('abcde')
print(new_tuple4)